name: Test on Windows (FPC 3.2.2)
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Free-Pascal
        run: |
          Invoke-WebRequest -Uri "http://downloads.freepascal.org/fpc/dist/3.2.2/i386-win32/fpc-3.2.2.i386-win32.exe" -OutFile "fpc-installer.exe"
          Start-Process -FilePath "fpc-installer.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait
      - name: Set up PATH
        run: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          $env:Path += ";C:\Program Files\Free Pascal\bin\i386-win32"
          echo "PATH=$env:Path" >> $env:GITHUB_ENV
      - name: Execute Tests
        run: pwsh -File ./scripts/run_tests.ps1 ci
