name: Test 
on:
  push:
    branches: [ "master" ]
    paths:
      - './cldr/**'
      - './src/**'
      - './tz_database_latest/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - './cldr/**'
      - './src/**'
      - './tz_database_latest/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Free-Pascal
        run: sudo apt-get install -y fpc
      - name: Execute Tests
        run: mkdir ./bin && fpc ./src/TZTest/TZTest.dpr -Fu./src/TZDBPK -Fu./src/TZDBLIB -FE./bin -FU./bin && ./bin/TZTest --format=plain --all --progress --sparse
